# Transformers Architecture with PyTorch Examples

In [2]:
%pip install torch

  Using cached typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)
  Using cached sympy-1.13.2-py3-none-any.whl.metadata (12 kB)
  Using cached networkx-3.3-py3-none-any.whl.metadata (5.1 kB)
  Using cached jinja2-3.1.4-py3-none-any.whl.metadata (2.6 kB)
  Using cached MarkupSafe-2.1.5-cp312-cp312-macosx_10_9_universal2.whl.metadata (3.0 kB)
  Using cached mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.1/62.1 MB 6.7 MB/s eta 0:00:0000:0100:01
Using cached typing_extensions-4.12.2-py3-none-any.whl (37 kB)
Using cached jinja2-3.1.4-py3-none-any.whl (133 kB)
Using cached networkx-3.3-py3-none-any.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 5.2 MB/s eta 0:00:00a 0:00:01
Using cached sympy-1.13.2-py3-none-any.whl (6.2 MB)
Using cached MarkupSafe-2.1.5-cp312-cp312-macosx_10_9_universal2.whl (18 kB)
Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)
Note: you may need to restart the kernel to use updated packages


## Transformer Overview

The Transformer model consists of an encoder and a decoder. Each of these components is made up of several layers of attention mechanisms and feed-forward networks.

![Transformer architecture](https://daleonai.com/images/screen-shot-2021-05-06-at-12.12.21-pm.png)

As for now we have reviewed **Self-Attention** and **Multiheaded Attention**, let's take a look on how to implement them with examples with PyTorch



### Self-Attention Calculation

The self-attention mechanism can be described with the following steps:

1. Compute Query, Key, and Value matrices from the input.
2. Calculate attention scores using the dot product of Query and Key.
3. Apply a Softmax function to the attention scores.
4. Compute the weighted sum of the Value vectors.



### PyTorch Implementation


In [71]:

import torch
import torch.nn.functional as F

def self_attention(Q, K, V):
    dimension = torch.sqrt(torch.Tensor([K.shape[-1]]))
    scores = torch.matmul(Q, K.transpose(-2,-1)) / dimension
    weights = F.softmax(scores, dim=-1)
    output = torch.matmul(weights, V)
    return output

# Example
Q = torch.randn(1, 3, 4)  # (batch_size, seq_len, embed_dim)
K = torch.randn(1, 3, 4)
V = torch.randn(1, 3, 4)

print(f'Q:{Q}\nK:{K}\nV:{V}')
attention_output = self_attention(Q, K, V)
print(f'Attention:{attention_output}')


Q:tensor([[[ 1.6851,  0.1665, -0.0917, -0.2914],
         [-0.8735,  0.8515,  1.1608,  0.1396],
         [-0.1546,  1.5666,  0.9541,  1.1648]]])
K:tensor([[[ 0.4788,  0.3367,  1.1149, -0.2138],
         [ 1.7596, -0.5329,  0.6616, -1.7132],
         [ 0.3233,  0.9728,  0.9566, -0.4169]]])
V:tensor([[[ 1.0031,  0.5750, -1.0804,  1.0226],
         [-2.3141,  0.3248, -0.1342, -0.5509],
         [-0.1072,  1.4614, -0.6232, -0.3182]]])
Attention:tensor([[[-1.3144,  0.5714, -0.3945, -0.2204],
         [ 0.0929,  0.9892, -0.7508,  0.1856],
         [ 0.1976,  1.0412, -0.7743,  0.1983]]])



## Positional Encodings



In the description of the original Transformer model, apart from the embeddings the authors provided
a mechanism to encode positions of the word.

They describe the positional encoding $PE$ in terms of cosines and sines of the positions of the words. These are not dependant
on the embeddings. Consider $i$ ranging from $0$ to $d_{model}/2$, and $pos$ the position of the embedding vector, then the 
$PE$ matrix is given by:

$$
\begin{align*}
PE(pos, 2i) &=\sin(\frac{pos}{l^{2i/d_{model}}}) \\
PE(pos, 2i+1) &=\cos(\frac{pos}{l^{2i/d_{model}}})
\end{align*}
$$

Here $l$ is a user defined scalar, in the paper _Attention is all you need_ they showcase $l=10000$.


## PyTorch Implementation


In [105]:
import torch
import math

class PositionalEncoding(torch.nn.Module):
    def __init__(self, d_model, max_len=5000, l=10000):

        super().__init__()

        self.encoding = torch.zeros(max_len, d_model)
        positions = torch.arange(0, max_len).unsqueeze(1)
        div_term = torch.exp(torch.arange(0, d_model, 2) * -(math.log(l) / d_model))
        self.encoding[:, 0::2] = torch.sin(positions * div_term)
        self.encoding[:, 1::2] = torch.cos(positions * div_term)
        self.encoding = self.encoding.unsqueeze(0)
    
    def forward(self, x):
        return x + self.encoding[:, :x.size(1)]

# Example
pos_encoding = PositionalEncoding(d_model=4)
x = torch.randn(1, 3, 4)
encoded_x = pos_encoding(x)
print(encoded_x)


tensor([[[ 8.0419e-01,  2.3076e-02, -1.8849e-03,  3.0204e-01],
         [ 5.9696e-01, -5.7712e-01,  3.4466e-01,  5.7928e-01],
         [ 2.1203e+00,  4.7336e-01,  1.4695e+00, -1.6983e+00]]])



# Encoder block


A Transformer encoder block consists of the following layers:

- Multi-Head Attention
- Add & Norm
- Feed-Forward Network
- Add & Norm


## PyTorch Implementation


In [111]:

import torch.nn as nn

class TransformerBlock(nn.Module):
    def __init__(self, d_model, nhead, dim_feedforward):
        super(TransformerBlock, self).__init__()
        self.attention = nn.MultiheadAttention(d_model, nhead)
        self.ffn = nn.Sequential(
            nn.Linear(d_model, dim_feedforward),
            nn.ReLU(),
            nn.Linear(dim_feedforward, d_model)
        )
        self.norm1 = nn.LayerNorm(d_model)
        self.norm2 = nn.LayerNorm(d_model)
        self.dropout = nn.Dropout(0.1)
    
    def forward(self, x):
        attn_output, _ = self.attention(x, x, x)
        x = x + self.dropout(attn_output)
        x = self.norm1(x)
        ffn_output = self.ffn(x)
        x = x + self.dropout(ffn_output)
        x = self.norm2(x)
        return x

# Example
transformer_block = TransformerBlock(d_model=4, nhead=2, dim_feedforward=8)
x = torch.randn(3, 1, 4)  # (seq_len, batch_size, d_model)
output = transformer_block(x)
print(output)


tensor([[[-1.5598, -0.1438,  1.0702,  0.6334]],

        [[-1.3429,  1.4606, -0.2265,  0.1089]],

        [[-0.4829,  0.0358,  1.5773, -1.1303]]],
       grad_fn=<NativeLayerNormBackward0>)


In [ ]:
import torch.nn as nn

class TransformerEncoder(nn.Module):
    def __init__(self, d_model, nhead, num_layers, dim_feedforward):
        super(TransformerEncoder, self).__init__()
        self.positional_encoding = PositionalEncoding(d_model)
        self.layers = nn.ModuleList([
            TransformerBlock(d_model, nhead, dim_feedforward)
            for _ in range(num_layers)
        ])
    
    def forward(self, x):
        x = self.positional_encoding(x)
        for layer in self.layers:
            x = layer(x)
        return x

# Example
model = TransformerEncoder(d_model=4, nhead=2, num_layers=2, dim_feedforward=8)
x = torch.randn(3, 1, 4)  # (seq_len, batch_size, d_model)
output = model(x)
print(output)


## Decoder Block

For the decoder, the implementation employs a **masking** mechanism in the self attention portion. To prevent illegal connections from happening, that is, for the
self attention in the masked decoder block to only allow "seeing" to past portions of the sequence we can use a triangular lower matrix:

$$
\operatorname{mask} = \begin{bmatrix}
1 & 0 & \cdots & 0 \\
1 & 1 & \cdots & 0 \\
\vdots & \vdots & \ddots & \vdots \\
1 & 1 & \cdots & 1 
\end{bmatrix}
$$

We will apply this mask to the $QK^T$ matrix making entries that don't match with the ones, $-\infty$, so they won't contribute anything to the Softmax calculation.

## PyTorch implementation

In [3]:
import torch
import torch.nn as nn
import torch.nn.functional as F

class MaskedMultiHeadAttention(nn.Module):
    def __init__(self, d_model, nhead):
        super(MaskedMultiHeadAttention, self).__init__()
        assert d_model % nhead == 0, "Embedding dimension must be divisible by number of heads"
        
        self.d_model = d_model
        self.nhead = nhead
        self.head_dim = d_model // nhead
        
        self.q_linear = nn.Linear(d_model, d_model)
        self.k_linear = nn.Linear(d_model, d_model)
        self.v_linear = nn.Linear(d_model, d_model)
        self.out_linear = nn.Linear(d_model, d_model)
        
        self.dropout = nn.Dropout(0.1)
    
    def forward(self, query, key, value, mask=None):
        batch_size = query.size(0)
        
        def shape(x):
            # (batch_size, seq_length, d_model) -> (batch_size, nhead, seq_length, head_dim)
            x = x.view(batch_size, -1, self.nhead, self.head_dim)
            return x.permute(0, 2, 1, 3)
        
        # Linear projections
        q = shape(self.q_linear(query))
        k = shape(self.k_linear(key))
        v = shape(self.v_linear(value))
        
        # Scaled dot-product attention
        scores = torch.matmul(q, k.transpose(-2, -1)) / (self.head_dim ** 0.5)
        
        if mask is not None:
            # Apply the mask to the attention scores
            scores = scores.masked_fill(mask == 0, float('-inf'))
        
        attn_weights = F.softmax(scores, dim=-1)
        attn_weights = self.dropout(attn_weights)
        
        # Weighted sum of values
        output = torch.matmul(attn_weights, v)
        
        # Concat heads and pass through final linear layer
        output = output.permute(0, 2, 1, 3).contiguous()
        output = output.view(batch_size, -1, self.d_model)
        
        return self.out_linear(output)

# Example usage:
d_model = 64
nhead = 8
seq_length = 20
attention = MaskedMultiHeadAttention(d_model, nhead)

# Random input tensors
query = torch.randn(1, seq_length, d_model)  # (batch_size, seq_length, d_model)
key = torch.randn(1, seq_length, d_model)
value = torch.randn(1, seq_length, d_model)

# Masking: assume that mask is of shape (batch_size, nhead, seq_length, seq_length)
mask = torch.tril(torch.ones(seq_length, seq_length)).unsqueeze(0).unsqueeze(0)  # Lower triangular matrix for causal mask
mask = mask.to(dtype=torch.bool)  # Convert to boolean mask

# Forward pass
output = attention(query, key, value, mask)
print(output)



tensor([[[-0.1126, -0.4043,  0.3415,  ...,  0.0902, -0.0898, -0.0392],
         [ 0.0580, -0.1321,  0.0879,  ...,  0.0350,  0.0390, -0.0620],
         [-0.0621,  0.1411,  0.0290,  ...,  0.0196,  0.1440, -0.0710],
         ...,
         [-0.1074, -0.0085, -0.0403,  ...,  0.0013, -0.0254, -0.1690],
         [-0.0945, -0.1382, -0.0164,  ...,  0.0912, -0.1101, -0.0983],
         [-0.0683, -0.0572, -0.0133,  ...,  0.0073, -0.0148, -0.1026]]],
       grad_fn=<ViewBackward0>)


We can finally assemble the PyTorch implementation of the Transformer architecture

## PyTorch Implementation

In [ ]:
import torch
import torch.nn as nn

class DecoderBlock(nn.Module):
    def __init__(self, d_model, nhead, dim_feedforward, mask):
        super(DecoderBlock, self).__init__()
        self.mask = mask
        self.transformer_block = TransformerBlock(d_model, nhead, dim_feedforward)
        self.masked_attn = MaskedMultiHeadAttention(d_model, nhead)
        self.dropout = nn.Dropout(0.1)
        self.norm = nn.LayerNorm(d_model)
    
    def forward(self, output, x):
        attn_output = self.masked_attn(output, output, output, self.mask)
        attn_output = output + self.dropout(attn_output)
        attn_output = self.norm(attn_output)
        x = self.transformer_block(x, x, attn_output)
        return x


class Transformer(nn.Module):
    def __init__(self, d_model, nhead, num_layers, dim_feedforward, mask):
        super(Transformer, self).__init__()
        self.encoder = TransformerEncoder(d_model, nhead, num_layers, dim_feedforward)
        self.masked_attn = nn.ModuleList([MaskedMultiHeadAttention(d_model, nhead)
                                          for _ in range(num_layers)])
    
    def forward(self, x):
        x = self.positional_encoding(x)
        for layer in self.layers:
            x = layer(x)
        return x

class TransformerEncoder(nn.Module):
    def __init__(self, d_model, nhead, num_layers, dim_feedforward):
        super(TransformerEncoder, self).__init__()
        self.positional_encoding = PositionalEncoding(d_model)
        self.layers = nn.ModuleList([
            TransformerBlock(d_model, nhead, dim_feedforward)
            for _ in range(num_layers)
        ])
    
    def forward(self, x):
        x = self.positional_encoding(x)
        for layer in self.layers:
            x = layer(x)
        return x

# Example
model = TransformerEncoder(d_model=4, nhead=2, num_layers=2, dim_feedforward=8)
x = torch.randn(3, 1, 4)  # (seq_len, batch_size, d_model)
output = model(x)
print(output)

Conclusion

In this notebook, we have explored the core components of the Transformer architecture, including self-attention, positional encoding, and the structure of Transformer blocks. We have also provided PyTorch implementations for each of these components.

Feel free to experiment with different configurations and datasets to better understand how Transformers work!

## Further reading

[Grant Sanderson on Transformers](https://www.youtube.com/watch?v=eMlx5fFNoYc)